#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SVG_DIR="$SCRIPT_DIR/svg"
OUT_DIR="$SCRIPT_DIR"
TRAY_DIR="$OUT_DIR/tray"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

# --- Check prerequisites ---
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "ERROR: '$1' not found. Install with: $2"
        exit 1
    fi
}

check_cmd rsvg-convert "brew install librsvg"
check_cmd magick "brew install imagemagick"

echo "=== Generating icons from SVGs ==="

# --- Dock icon via Tauri CLI (recommended by Tauri docs) ---
echo "→ Dock icon (via tauri icon)..."
MASTER_PNG=$(mktemp /tmp/dock-icon-XXXXXX.png)
rsvg-convert -w 1024 -h 1024 "$SVG_DIR/dock-icon.svg" -o "$MASTER_PNG"
magick "$MASTER_PNG" -type TrueColorAlpha "PNG32:$MASTER_PNG"
(cd "$PROJECT_DIR" && npx tauri icon "$MASTER_PNG")
rm -f "$MASTER_PNG"

# --- Tray icons (custom, not handled by tauri icon) ---
echo "→ Tray icons..."
mkdir -p "$TRAY_DIR"

# Disconnected: 22x24 @1x and 44x48 @2x
rsvg-convert -w 22 -h 24 "$SVG_DIR/tray-disconnected.svg" -o "$TRAY_DIR/disconnected.png"
rsvg-convert -w 44 -h 48 "$SVG_DIR/tray-disconnected.svg" -o "$TRAY_DIR/disconnected@2x.png"

# Connected: 22x24 @1x and 44x48 @2x
rsvg-convert -w 22 -h 24 "$SVG_DIR/tray-connected.svg" -o "$TRAY_DIR/connected.png"
rsvg-convert -w 44 -h 48 "$SVG_DIR/tray-connected.svg" -o "$TRAY_DIR/connected@2x.png"

echo ""
echo "=== Done! ==="
echo "Dock:  Generated by 'tauri icon' (icon.png, icon.icns, icon.ico, etc.)"
echo "Tray:  tray/disconnected.png, tray/disconnected@2x.png"
echo "       tray/connected.png, tray/connected@2x.png"
